hl.layer_rule({ match = { namespace = "bar" }, blur = true })
hl.layer_rule({ match = { namespace = "notification-popups" }, blur = true })
hl.layer_rule({ match = { namespace = "right-panel" }, blur = true })
hl.layer_rule({ match = { namespace = "left-panel" }, blur = true })
hl.layer_rule({ match = { namespace = "wallpaper-switcher" }, blur = true })
hl.layer_rule({ match = { namespace = "app-launcher" }, blur = true })
hl.layer_rule({ match = { namespace = "user-panel" }, blur = true })
hl.layer_rule({ match = { namespace = "osd" }, blur = true })
hl.layer_rule({ match = { namespace = "keystroke-visualizer" }, blur = true })
hl.layer_rule({ match = { namespace = "always-on-widget" }, blur = true })

hl.layer_rule({ match = { namespace = "bar" }, blur_popups = true })
hl.layer_rule({ match = { namespace = "app-launcher" }, blur_popups = true })
hl.layer_rule({ match = { namespace = "left-panel" }, blur_popups = true })

hl.layer_rule({ match = { namespace = "bar" }, ignore_alpha = 0.1 })
hl.layer_rule({ match = { namespace = "notification-popups" }, ignore_alpha = 0.1 })
hl.layer_rule({ match = { namespace = "right-panel" }, ignore_alpha = 0.1 })
hl.layer_rule({ match = { namespace = "left-panel" }, ignore_alpha = 0.1 })
hl.layer_rule({ match = { namespace = "wallpaper-switcher" }, ignore_alpha = 0.1 })
hl.layer_rule({ match = { namespace = "app-launcher" }, ignore_alpha = 0.1 })
hl.layer_rule({ match = { namespace = "user-panel" }, ignore_alpha = 0.1 })
hl.layer_rule({ match = { namespace = "osd" }, ignore_alpha = 0.1 })
hl.layer_rule({ match = { namespace = "popups" }, ignore_alpha = 0.1 })
hl.layer_rule({ match = { namespace = "keystroke-visualizer" }, ignore_alpha = 0.1 })
hl.layer_rule({ match = { namespace = "always-on-widget" }, ignore_alpha = 0.1 })

hl.layer_rule({ match = { namespace = "hyprpaper" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "mpvpaper" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "selection" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "user-panel" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "hyprpicker" }, animation = "fade" })
hl.layer_rule({ match = { namespace = "app-launcher" }, animation = "fade" })
